/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImagePanel.java
 *
 * Created on 21-Dec-2011, 8:39:52 PM
 */
package spaceinvaders3d;

/**
 *
 * @author Stephen Wen
 */

import java.awt.*;
import java.beans.Beans;
public class ImagePanel extends javax.swing.JPanel {

    /** Creates new form ImagePanel */
    public ImagePanel() {
        initComponents();
    }
   @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); //paint background
        if(!Beans.isDesignTime())
        {
            g.setColor(Color.WHITE);
            g.drawRect(100, 100, 100, 100);
        }
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
